(source melpa)

(depends-on "ag")
(depends-on "eldoc")
(depends-on "evil")
(depends-on "flx-ido")
(depends-on "google-c-style")
(depends-on "ido-vertical-mode")
(depends-on "ir-black-theme")
(depends-on "pallet")
(depends-on "powerline")
(depends-on "projectile")
(depends-on "use-package")
